// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU1vZLGXI0oajZ1jGvOn-B6dKYnbesrYg',
    appId: '1:671586938060:web:f765f3f2ae20d84d58e669',
    messagingSenderId: '671586938060',
    projectId: 'catalogo-peliculas-aac64',
    authDomain: 'catalogo-peliculas-aac64.firebaseapp.com',
    storageBucket: 'catalogo-peliculas-aac64.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcSEI-d_LQTDjPJcARgVFtM_4UaLqspXs',
    appId: '1:671586938060:android:eab5f234e1661e5658e669',
    messagingSenderId: '671586938060',
    projectId: 'catalogo-peliculas-aac64',
    storageBucket: 'catalogo-peliculas-aac64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5H9rcbAxMO9oPkpcV14GT9JlnKaZcB38',
    appId: '1:671586938060:ios:e90fc0d699d050b758e669',
    messagingSenderId: '671586938060',
    projectId: 'catalogo-peliculas-aac64',
    storageBucket: 'catalogo-peliculas-aac64.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1Catalogodepeliculas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5H9rcbAxMO9oPkpcV14GT9JlnKaZcB38',
    appId: '1:671586938060:ios:e90fc0d699d050b758e669',
    messagingSenderId: '671586938060',
    projectId: 'catalogo-peliculas-aac64',
    storageBucket: 'catalogo-peliculas-aac64.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1Catalogodepeliculas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU1vZLGXI0oajZ1jGvOn-B6dKYnbesrYg',
    appId: '1:671586938060:web:4753e3af0b465abe58e669',
    messagingSenderId: '671586938060',
    projectId: 'catalogo-peliculas-aac64',
    authDomain: 'catalogo-peliculas-aac64.firebaseapp.com',
    storageBucket: 'catalogo-peliculas-aac64.firebasestorage.app',
  );
}
